import './globals.css'
import type { Metadata } from 'next'
import { Red_Hat_Display } from 'next/font/google'



const red = Red_Hat_Display({ 
  weight: ['400', '500','600', '700'],
  subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'HOS - Software para Farmácias',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={red.className}>
      {children}
        </body>
    </html>
  )
}
