import { Header } from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'
import { Red_Hat_Display } from 'next/font/google'

const red = Red_Hat_Display({ 
  weight: ['400', '500', '700'],
  subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={red.className}>
        <Header />
        {children}</body>
    </html>
  )
}
